# vim: ft=ansible :
---
# tasks file for config
- name: Create datadir
  file:
    path: "{{ galera_mysql_datadir }}"
    state: directory
    owner: "{{ mariadb_daemon_user }}"
    group: "{{ mariadb_daemon_user }}"
    mode: 0755
    setype: mysqld_db_t
  when: galera_mysql_datadir is defined

- name: Setup datadir
  ini_file:
    path: "{{ mariadb_config_dir }}server.cnf"
    section: mysqld
    option: datadir
    value: "{{ galera_mysql_datadir }}"

- name: Create mysqld logfile
  file:
    path: "{{ mariadb_log }}"
    state: touch
    owner: "{{ mariadb_daemon_user }}"
    group: "{{ mariadb_daemon_user }}"
  when: mariadb_log is defined

- name: Setup mysqld general-log
  ini_file:
    path: "{{ mariadb_config_dir }}server.cnf"
    owner: "{{ mariadb_daemon_user }}"
    group: "{{ mariadb_daemon_user }}"
    section: mysqld
    option: general-log
    value: on

- name: Setup mysqld general-log-file
  ini_file:
    path: "{{ mariadb_config_dir}}server.cnf"
    section: mysqld
    option: general-log-file
    value: "{{ mariadb_log }}"
  when: mariadb_log is defined

- name: Create mysqld logfile
  file:
    path: "{{ mariadb_log_error }}"
    owner: mysql
    group: mysql
    state: touch
  when: mariadb_log_error is defined

- name: Setup mysqld error log
  ini_file:
    path: "{{ mariadb_config_dir }}server.cnf"
    owner: "{{ mariadb_daemon_user }}"
    group: "{{ mariadb_daemon_user }}"
    section: mysqld
    option: log-error
    value: "{{ mariadb_log_error }}"
  when: mariadb_log_error is defined

- name: Create mysqld PID dir
  file:
    path: "{{ mariadb_pid_file | dirname }}"
    state: directory
    owner: "{{ mariadb_daemon_user }}"
    group: "{{ mariadb_daemon_user }}"
    mode: 0755
    setype: mysqld_db_t

- name: Setup mysqld listening port to {{ mariadb_server_port }}
  ini_file:
    path: "{{ mariadb_config_dir }}server.cnf"
    section: server
    option: port
    value: "{{ mariadb_server_port }}"

- name: Setup mysql client port to {{ mariadb_client_port }}
  ini_file:
    path: "{{ mariadb_config_dir }}server.cnf"
    section: client
    option: port
    value: "{{ mariadb_client_port }}"

